### ISSUE TITLE
Confused how to use it like `cd ..` too

### ISSUE THREAD

**Issue by nikivdev** [ClementNerma/Jumpy#5]
I had this alias:

`alias d="z"`

I now wanted to move to jumpy and did:

`alias d="jumpy"`

I thought jumpy worked like z but faster. Which means if I am here:

```
ls
c/  config/  deno/  elixir/  go/  lean/  mojo/  new/  nikiv.dev/  nix/  ocaml/  org/  other/  py/  raycast/  rust/  snippets/  swift/  test/  ts/  zig/
```

I don't get error when I try to just do `jumpy <dir>` (that exists)

```
d deno
error: unrecognized subcommand 'deno'

  tip: a similar subcommand exists: 'del'

Usage: jumpy [OPTIONS] <COMMAND>

For more information, try '--help'.
```

Perhaps I misunderstand something.

**Comment by nikivdev** [comment]
https://github.com/ajeetdsouza/zoxide is `z` for reference

**Comment by ClementNerma** [comment]
Actually, just like Zoxide, you don't call the binary directly ; you call a shell hook or alias.

For instance, if you use ZSH, you need to copy-paste the `z` function example shown in the README.

```zsh
function z() {
    local result=$(jumpy query "$1" --checked --after "$PWD")

    if [[ -n $result ]]; then
        export __JUMPY_DONT_REGISTER=1
        cd "$result"
        export __JUMPY_DONT_REGISTER=0
    fi
}

function jumpy_handler() {
    if (( $__JUMPY_DONT_REGISTER )); then
        return
    fi

    emulate -L zsh
    jumpy inc "$PWD"
}

chpwd_functions=(${chpwd_functions[@]} "jumpy_handler")
```

The first part (the `z` function) actually calls `jumpy query <your text>` and _then_ `cd`s into that.

The second part (`jumpy_handler`) performs a registration so that everytime you go into a new directory it is registered by Jumpy.
